name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy over SSH
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@13.203.230.174 << 'EOF'
            cd node-docker-app
            git pull origin master
            docker stop mynodeapp || true
            docker rm mynodeapp || true
            docker build -t node-docker-app .
            docker run -d -p 80:80 --name mynodeapp node-docker-app
          EOF
